### ISSUE TITLE
Jump doesn't always work

### ISSUE THREAD

**Issue by xylude** [DigitalzombieTLD/Townscaper-LittleFirstPerson#1]
I noticed the jump doesn't always work, perhaps you should move the jump logic (https://github.com/DigitalzombieTLD/Townscaper-LittleFirstPerson/blob/0.8.0/FirstPersonController.cs#L299) from FixedUpdate to Update would solve it?

**Comment by DigitalzombieTLD** [comment]
I always forget to look at the Issues. Sorry!

Took the jump out and switched to jetpack-based movement. The first version was a third party script that I modified now. The whole mod is a mess, I should really clean it up sometime. 

But for now, I'm preparing the next release. Hopefully today! So ... fixed :D
